import type { HotzonesResponse } from "@shared/types";

/**
 * 離線示範資料：API 無法連線時的後備展示。
 * 依 CONTRIBUTING 規則，此資料永遠以「示範」明確標示，不可當成真實市場資料。
 */

export const DEMO_HOTZONES: HotzonesResponse = {
  asOf: "2026-09-04",
  generatedAt: "",
  summary: {
    advance: 1292,
    decline: 466,
    flat: 219,
    totalValue: 10065.0,
    institutionalNet: 552.1,
    institutionalCoverage: "示範數值",
  },
  industryZones: [],
  highlights: {
    sentiment: { value: 73, label: "樂觀", advance: 1292, decline: 466 },
    topFlow: [],
    whales: [],
  },
  zones: [
    {
      id: "demo-ai",
      name: "電腦及週邊設備業",
      count: 93,
      flowValue: 213.4,
      changePct: 2.4,
      turnoverShare: 0.18,
      turnoverValue: 1811.7,
      gainers: 79,
      losers: 12,
      flat: 2,
      breadth: 85,
      components: { flow: 96, price: 92, volume: 88, breadth: 85 },
      score: 94.8,
      status: "聚焦",
      topStocks: [],
    },
    {
      id: "demo-semi",
      name: "半導體業",
      count: 126,
      flowValue: 1.4,
      changePct: 1.2,
      turnoverShare: 0.21,
      turnoverValue: 2113.6,
      gainers: 95,
      losers: 25,
      flat: 6,
      breadth: 75,
      components: { flow: 52, price: 74, volume: 97, breadth: 75 },
      score: 83.1,
      status: "聚焦",
      topStocks: [],
    },
    {
      id: "demo-opto",
      name: "光電業",
      count: 69,
      flowValue: 7.0,
      changePct: 0.6,
      turnoverShare: 0.07,
      turnoverValue: 704.5,
      gainers: 44,
      losers: 20,
      flat: 5,
      breadth: 64,
      components: { flow: 61, price: 58, volume: 61, breadth: 64 },
      score: 80.0,
      status: "升溫",
      topStocks: [],
    },
    {
      id: "demo-ship",
      name: "航運業",
      count: 48,
      flowValue: 10.4,
      changePct: -0.4,
      turnoverShare: 0.05,
      turnoverValue: 503.2,
      gainers: 16,
      losers: 28,
      flat: 4,
      breadth: 33,
      components: { flow: 66, price: 42, volume: 48, breadth: 33 },
      score: 52.0,
      status: "分歧",
      topStocks: [],
    },
    {
      id: "demo-mem",
      name: "記憶體相關業",
      count: 19,
      flowValue: -7.1,
      changePct: -1.8,
      turnoverShare: 0.03,
      turnoverValue: 301.9,
      gainers: 5,
      losers: 13,
      flat: 1,
      breadth: 26,
      components: { flow: 34, price: 25, volume: 31, breadth: 26 },
      score: 29.0,
      status: "退潮",
      topStocks: [],
    },
  ],
  sources: ["離線示範資料"],
  notes: [
    "API 未連線：目前顯示離線示範資料，僅供介面預覽，不可當成真實市場資料。",
  ],
};
